feat: fallback to slotted trigger when query fails #28
AlaskaAirlines/auro-popover pull request #34
Opened 2021-08-17 23:42 UTC by geoffrich

# Alaska Airlines Pull Request

Fixes #28

## Summary:

When auro-button was used as the popover trigger in a Svelte application, the trigger would not be initialized properly. This is because the button `id` was being set as a property, so `querySelector` didn't work. 

At first I tried reflecting `id` to an attribute on `auro-button` so that `querySelector` could find it, but that was not reflected by the button until after popover had initialized the trigger, and the same problem occurred.

Instead, I chose to get the node assigned to the trigger slot, and use that if we couldn't find the trigger using `querySelector`. It could be possible to use this as our primary method of finding the trigger; however, I wasn't 100% confident that this wouldn't break existing uses of popover.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-08-18 00:06 UTC, blackfalcon requested changes
I see how this is working and the test scenarios, but don't you think we need to mention this on the demo page?

2021-08-18 16:30 UTC, geoffrich commented
@blackfalcon good callout. Should all of the demo examples be updated to not use the `for` attribute and rely on the slot placement? I think that makes for a cleaner API. I can update the tests too.

We can have a single example of the `for` / `id` pair on the demo page and mention that it's no longer necessary, but is still supported for the time being.

2021-08-23 20:14 UTC, blackfalcon commented
@geoffrich please update the demo examples per your suggestion.

2021-08-30 20:27 UTC, blackfalcon approved these changes
I really like this PR. This pushes an idea forward and deprecates an old idea without forcing a breaking change.

2021-08-30 20:28 UTC, merged

2021-08-30 20:31 UTC, AuroDesignSystem commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-popover/v/2.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-popover/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: