Add brackets around fallback values
AlaskaAirlines/auro-popover pull request #74
Opened 2024-07-08 21:51 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Add brackets around fallback options so that the values get compiled

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-07-08 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-popover?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-popover?pullRequest=74) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jordanjones243<br/>:x: semantic-release-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-popover?pullRequest=74) it.</sub>

2024-07-09 21:26 UTC, blackfalcon requested changes
There is a lot more here in this PR other than updating the Sass. Can you please maybe break up some of these commits to be specific as to the work done, or at least update the PR and the comment descriptions as to what all happened in this PR?

2024-07-09 21:26 UTC, blackfalcon commented on CHANGELOG.md
> +
Why is this in the PR?

2024-08-09 19:06 UTC, jordanjones243 commented
This PR will be closed and the work is addressed in this separate PR:
- https://github.com/AlaskaAirlines/auro-popover/pull/75

2024-08-09 19:06 UTC, closed without merging